import './globals.css'
import LayoutComponent from '../components/layout/LayoutComponent'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <LayoutComponent>
      {children}
    </LayoutComponent>
  )
}
